#ifndef DEFINE_LOG_TYPE
    #define DEFINE_LOG_TYPE(a)
#endif
#ifndef DEFINE_CLASS
    #define DEFINE_CLASS(a)
#endif

/* All the classes must be defined here */
    DEFINE_CLASS( TI_CLASS_NULL )   /* this must be the first class id */
    DEFINE_CLASS( TI_GENERIC )      /* this is used by the system */

/*  CURRENCY_CONVERTER CLASS */
    DEFINE_CLASS( C_MUI_CURRENCY_CONVERTER)      /* this is used by your project if required */




/* KRUSTY UTT TEST CLASS */
    DEFINE_CLASS( C_UTT_TEST )      /* this is used by your project if required */
    DEFINE_CLASS( C_UTT_TEST_IDLE )
    DEFINE_CLASS( C_UTT_TEST_VOICECALLS )
    DEFINE_CLASS( C_UTT_TEST_NWRK_INTEGRATION )
    DEFINE_CLASS( C_MUI_SS_TEST_HARNESS )
    DEFINE_CLASS( C_MUI_TREE_TEST )

    DEFINE_CLASS( C_MUI_PSS_TEST_HARNESS )

/* KRUSTY TEXT EDITOR CLASS */
    DEFINE_CLASS( TI_MUI_TEXT_EDITOR )

/* C_GL_UTILS_PROJECT */
    DEFINE_CLASS( C_LIB_BITS )
    DEFINE_CLASS( C_LIB_IMAGE )
    DEFINE_CLASS( C_LIB_STR_CONVERT )
    DEFINE_CLASS( C_SAFE_STRING )
    DEFINE_CLASS( TS_NU_TASK_TIMER )
    DEFINE_CLASS( TS_PHONE_NUMBER_INFO )
    DEFINE_CLASS( TS_PHONE_NUMBER )
    DEFINE_CLASS( TS_PHONE_NAME )
    DEFINE_CLASS( UTF )
    DEFINE_CLASS( UNI )
    DEFINE_CLASS( TS_UNIQUE_ID )


/* C_UI_GENERAL_PROJECT */
    DEFINE_CLASS( TI_MUI_APP_INTERFACE )
    DEFINE_CLASS( C_MUI_DISPLAY_MESSAGE )
    DEFINE_CLASS( C_MUI_APP_STATUS_BAR )
    DEFINE_CLASS( C_MUI_ENTER_PIN_CODE )
    DEFINE_CLASS( C_MUI_VERIFY_PIN )
    DEFINE_CLASS( C_MUI_APP_ICON_MANAGER )
    DEFINE_CLASS( C_MUI_APP_ICONS )
    DEFINE_CLASS( C_MUI_APP_MENU )
    DEFINE_CLASS( C_UTT_COMMON )    /* this is used by c_ui_common project */
    DEFINE_CLASS( C_MUI_FILE_SELECTOR_DLG )
    DEFINE_CLASS( C_MUI_TEXT_EDITOR_DLG )
    DEFINE_CLASS( C_MUI_CALENDAR_DLG )
    DEFINE_CLASS( C_MUI_VIDEO_CALL )

/* C_UI_CALL_LOGS */
    DEFINE_CLASS( TI_CALL_LOGS_INTERFACE )
    DEFINE_CLASS( TI_MUI_CALL_LOGS_INTERFACE )


/* C_UI_DATA_CALLS_PROJECT */
    DEFINE_CLASS( TI_MUI_DATACALLS_INTERFACE )
    DEFINE_CLASS( C_MUI_DATACALLS )
    DEFINE_CLASS( C_MUI_CALL_DEFLECTION )
    DEFINE_CLASS( C_MUI_DATA_CALLS_TEST )
    DEFINE_CLASS( C_MUI_DATA_SETTINGS )
    DEFINE_CLASS( C_MUI_DATA_ALARM )
    DEFINE_CLASS( C_MUI_DATA_CALLS_APNS_ACCESS )
	DEFINE_CLASS( C_MUI_APP_DATACALL_CLEARING )


/* C_UI_IDLE_PROJECT */
    DEFINE_CLASS( TI_MUI_IDLE_INTERFACE )
    DEFINE_CLASS( C_MUI_EMERGENCY_CALL )
    DEFINE_CLASS( C_MUI_MODE )

/* C_UI_MESSAGING_PROJECT */
/* vvv 26/01/04 fishe1g NSOFT00016229 */
#if 0
//  DEFINE_CLASS( TI_MUI_MESSAGING_INTERFACE )
#endif
/* ^^^ 26/01/04 fishe1g NSOFT00016229 */
    DEFINE_CLASS( C_MUI_APP_MESSAGING )
    DEFINE_CLASS( C_MUI_MESSAGING_POPUP )
    DEFINE_CLASS( C_MUI_SMS_SEND )
    DEFINE_CLASS( C_MUI_SMS_SAVE )
    DEFINE_CLASS( C_MUI_MSGS_DELETE )
    DEFINE_CLASS( C_MUI_SMS_LIBRARY )
    DEFINE_CLASS( C_MUI_MSGS_CONFIGURE )

/* C_UI_MULTIMEDIA_PROJECT */

/* C_UI_NWRK_REG_PROJECT */

/* C_UI_PHONEBOOK_PROJECT */
    DEFINE_CLASS( TI_MUI_PHONE_BOOK_INTERFACE )
    DEFINE_CLASS( C_MUI_PBK_GET_RESOURCE )
    DEFINE_CLASS( C_MUI_PBK_VIEW )
    DEFINE_CLASS( C_MUI_PBK_SEARCH )
    DEFINE_CLASS( C_MUI_PBK_STATUS )
    DEFINE_CLASS( C_MUI_PBK_CREATE )
    DEFINE_CLASS( C_MUI_ENTER_DETAILS )
    DEFINE_CLASS( C_MUI_PBK_SELECT_LOCATION )
    DEFINE_CLASS( C_MUI_PBK_DELETE )
    DEFINE_CLASS( C_MUI_PBK_EDIT )
    DEFINE_CLASS( C_MUI_PBK_MOVE_COPY )
    DEFINE_CLASS( C_MUI_PBK_SWAP )
    DEFINE_CLASS( C_MUI_PBK_GROUPS )
    DEFINE_CLASS( C_MUI_PBK_GROUP_EDIT )
    DEFINE_CLASS( TI_PHONE_BOOK_INTERFACE )
    DEFINE_CLASS( C_UTT_PBK_TEST )
    DEFINE_CLASS( C_MUI_PBK_ATTRIBUTES )
    DEFINE_CLASS( C_MUI_PBK_DM_API )
    DEFINE_CLASS( C_MUI_PBK_PROFILES )

/* C_UI_POW_PROJECT */
    DEFINE_CLASS( TI_MUI_POWER_INTERFACE )
    DEFINE_CLASS( C_MUI_POWER_UP )
    DEFINE_CLASS( C_MUI_POWER_DOWN )
    DEFINE_CLASS( C_MUI_RESTORE_DEFAULTS )
    DEFINE_CLASS( C_MUI_RESET_MENU )

/* C_UI_SAT_APP_PROJECT */
    DEFINE_CLASS( TI_MUI_SAT_INTERFACE )
    DEFINE_CLASS( C_SATA_PERFORM_CMDS )
    DEFINE_CLASS( C_SATA_DTT_PLT )
/* vvv 26/01/04 fishe1g NSOFT00016229 */
#if 0
//  DEFINE_CLASS( C_SATA_GET_INPUT_INKEY )
#endif
/* ^^^ 26/01/04 fishe1g NSOFT00016229 */
    DEFINE_CLASS( C_SATA_SEND_SS_USSD )
    DEFINE_CLASS( C_SATA_SEND_SMS )
    DEFINE_CLASS( C_SATA_SETUP_CALL )
    DEFINE_CLASS( C_SATA_SETUP_MENU )
    DEFINE_CLASS( C_SATA_MORE_TIME )
    DEFINE_CLASS( C_SATA_SELECT_ITEM )
    DEFINE_CLASS( C_SATA_SETUP_IDLE_MODE_TEXT )
    DEFINE_CLASS( C_SATA_SETUP_EVENTLIST )
    DEFINE_CLASS( C_SATA_GET_FOCUS )
    DEFINE_CLASS( C_SATA_ENVELOPE )
    DEFINE_CLASS( C_SATA_REFRESH )
    DEFINE_CLASS( C_SATA_SEND_DTMF )
    DEFINE_CLASS( C_SATA_CALL_CONTROL )
    DEFINE_CLASS( C_SATA_DISPLAY_STATUS_SCREEN )

/* C_UI_SAT_SERVER_PROJECT */

/* C_UI_SS_PROJECT */
    DEFINE_CLASS( TI_MUI_SS_INTERFACE )
    DEFINE_CLASS( C_MUI_DIVERT )
    DEFINE_CLASS( C_MUI_BARRING )
    DEFINE_CLASS( C_MUI_CLIR )
    DEFINE_CLASS( C_MUI_CW)
    DEFINE_CLASS( C_MUI_SS_LIB )
    DEFINE_CLASS( C_MUI_UNSOLICITED_SS )
    DEFINE_CLASS( C_MUI_UNSOLICITED_SS_PARENT )
    DEFINE_CLASS( C_MUI_AUTOCHECK )
    DEFINE_CLASS( C_MUI_CALL_INFO )

/* C_UI_TEST_PROJECT */
/* vvv 26/01/04 fishe1g NSOFT00016229 */
#if 0
//  DEFINE_CLASS( C_MUI_TEST_APP )  /* this is used by c_ui_test project */
#endif
/* ^^^ 26/01/04 fishe1g NSOFT00016229 */
    DEFINE_CLASS( C_MUI_TEST_BLANK_APP )
    DEFINE_CLASS( C_UTT_TEST_STRUCTURE )
    DEFINE_CLASS( TC_UTT_TEST_TIMER )


    DEFINE_CLASS( C_CLASS_GENERATOR )
    DEFINE_CLASS( C_UTT_TEST_CONSTANT )
    DEFINE_CLASS( C_UTT_TEST_CONSTANT_CLASS )
    DEFINE_CLASS( C_UTT_TEST_CONSTANT_CLASS_INST )

    DEFINE_CLASS( C_UTT_TEST_STATIC )
    DEFINE_CLASS( C_UTT_TEST_STATIC_ACTIVE )
    DEFINE_CLASS( C_UTT_TEST_STATIC_CLASS )
    DEFINE_CLASS( C_UTT_TEST_STATIC_CLASS_INST )

    DEFINE_CLASS( C_UTT_TEST_DYNAMIC_ACTIVE )
    DEFINE_CLASS( C_UTT_TEST_DYNAMIC )
    DEFINE_CLASS( C_UTT_TEST_DYNAMIC_CLASS )
    DEFINE_CLASS( C_UTT_TEST_DYNAMIC_CLASS_INST )

    DEFINE_CLASS( C_UTT_TEST_DEFAULT )
    DEFINE_CLASS( C_UTT_TEST_DEFAULT_ACTIVE )
    DEFINE_CLASS( C_UTT_TEST_DEFAULT_CLASS )
    DEFINE_CLASS( C_UTT_TEST_DEFAULT_CLASS_INST )
    DEFINE_CLASS( C_UTT_TEST_STATE_MACHINE )
    DEFINE_CLASS( TC_UTT_TEST_REALISE )



/* C_UI_TEST_BROWSER */
    DEFINE_CLASS( TI_MUI_TEST_BROWSER_INTERFACE )

    DEFINE_CLASS( TI_MUI_FEP_TEXTEDIT )
/* vvv 26/01/04 fishe1g NSOFT00016229 */
#if 0
/* STUB FILE MANAGER */
//  DEFINE_CLASS(TI_MUI_APP_FILE_SELECTOR_INTERFACE)
#endif
/* ^^^ 26/01/04 fishe1g NSOFT00016229 */



/* C_UI_VOICECALLS_PROJECT */
    DEFINE_CLASS( TI_MUI_VOICE_CALLS_INTERFACE )
    DEFINE_CLASS( C_MUI_APP_CALL_CLEARING )
    DEFINE_CLASS( C_MUI_APP_CALL_TIMER )
    DEFINE_CLASS( C_MUI_APP_CCBS )
    DEFINE_CLASS( C_MUI_MDT_TEST )
    DEFINE_CLASS( C_MUI_APP_CALL_MENU)
    DEFINE_CLASS( C_MUI_CD_NUMBER_SETTING)
    DEFINE_CLASS( C_MUI_AOC_MENU)
    
/* C_UI_SECURITY_PROJECT */
    DEFINE_CLASS( C_MUI_POWER_UP_CHECKS )
    DEFINE_CLASS( C_MUI_SECURITY_MENU )
    DEFINE_CLASS( C_MUI_UPDATE_PIN_CODE )
    DEFINE_CLASS( C_MUI_CHANGE_PIN_CODE )
    DEFINE_CLASS( C_MUI_DIAL_LOCK )
    DEFINE_CLASS( TI_MUI_SECURITY_PIN_INTERFACE )
    DEFINE_CLASS( C_MUI_PIN_VERIFICATION )
    DEFINE_CLASS( C_MUI_PIN_ENABLE_CONTROL )
    DEFINE_CLASS( C_MUI_SECURITY_TEST )
    DEFINE_CLASS( C_MUI_LOCK_CMDS )
    DEFINE_CLASS( C_MUI_FIXED_DIAL )
    DEFINE_CLASS( TI_MUI_SECURITY_INTERFACE )

/* C_UI_VOICEMAIL_PROJECT */
    DEFINE_CLASS( TI_MUI_VMAIL_INTERFACE )
    DEFINE_CLASS( C_MUI_APP_VOICE_MAIL_MENU )
    DEFINE_CLASS( C_MUI_APP_VOICE_MAIL_DIAL_ON_DELIVERY )
    DEFINE_CLASS( C_UTT_TEST_VM )

/* C_UI_NOTEPAD_PROJECT */
    DEFINE_CLASS( C_MUI_NOTEPAD )
    DEFINE_CLASS( C_MUI_NOTEPAD_DELETE_ALL )
    DEFINE_CLASS( C_MUI_NOTEPAD_SEND )


/* C_UI_MELODY_COMPOSER_PROJECT */
    DEFINE_CLASS( C_MUI_MC )
    DEFINE_CLASS( C_MUI_MC_ADD )
    DEFINE_CLASS( C_MUI_MC_EDIT )
    DEFINE_CLASS( C_MUI_MC_DELETE )
    DEFINE_CLASS( C_MUI_MC_PLAY )
    DEFINE_CLASS( C_MUI_MC_ENTER_DATA )


/* C_UI_NWRK_REG_APP_PROJECT */
    DEFINE_CLASS( C_UTT_TEST_NWRK )
    DEFINE_CLASS( TI_MUI_NWRK_REG_INTERFACE )
    DEFINE_CLASS( C_MUI_NWRK_REG_APP )
    DEFINE_CLASS( C_MUI_NWRK_REG_PREF_PLMN )
    DEFINE_CLASS( C_MUI_NWRK_REG_SELECTION )
    DEFINE_CLASS( C_MUI_NWRK_REG_APN ) 
    DEFINE_CLASS( C_MUI_NWRK_REG_AREA_MODE )
    DEFINE_CLASS( C_MUI_NWRK_REG_GPRS )
    DEFINE_CLASS( C_MUI_NWRK_REG_PREF_MODE )
    

/* C_UI_CALCULATOR_PROJECT */
    DEFINE_CLASS( C_MUI_CALCULATOR )

/* C_MUI_DAYS_CALC_PROJECT */
    DEFINE_CLASS( C_MUI_DAYS_CALC )

/* C_MUI_TO_DO_PROJECT */
	DEFINE_CLASS(C_MUI_TODO_MAIN)

/* C_UI_GENERAL_DISPLAY_PROJECT */
    DEFINE_CLASS( TI_MUI_GEN_DISPLAY_INTERFACE )

/* C_UI_SMS_CB_PROJECT */
    DEFINE_CLASS( TI_MUI_CB_INTERFACE )
    DEFINE_CLASS( C_MUI_CB_CBMID )
    DEFINE_CLASS( C_MUI_CB_MAIN_MENU )
    DEFINE_CLASS( C_MUI_CB_MSG_SCREEN )


/* C_MUI_DATE_CALC_PROJECT */
    DEFINE_CLASS( C_MUI_DATE_CALC )

/* C_UI_SCHEDULE_PROJECT */
    DEFINE_CLASS( C_MUI_SCHD_MAIN )
    DEFINE_CLASS( C_MUI_SCHD_ALARM )
    DEFINE_CLASS( C_MUI_SCHD_DELETE )
    DEFINE_CLASS( C_MUI_SCHD_ADD_EDIT )

/* C_UI_CONFIG_PROJECT */
    DEFINE_CLASS( TI_MUI_CONFIGURE_INTERFACE)
    DEFINE_CLASS( C_MUI_MODE_SELECT )
    DEFINE_CLASS( C_MUI_MODE_CONFIGURE )
    DEFINE_CLASS( C_MUI_CNT_PANEL)
    DEFINE_CLASS( C_MUI_CLOCK)
    DEFINE_CLASS( C_MUI_VT)
    DEFINE_CLASS( UTT_TEST_CONFIGURE )

/* C_UI_ALS_PROJECT */
    DEFINE_CLASS( C_MUI_APP_ALS_MENU )
    DEFINE_CLASS( TI_MUI_ALS_INTERFACE )
    DEFINE_CLASS( C_UTT_TEST_ALS )


/* C_UI_GPRS project */
    DEFINE_CLASS( TI_MUI_GPRS_INTERFACE )

    /* TI_MUI_MULTI_WINDOW_INTERFACE */
    //DEFINE_CLASS( TI_MUI_MULTI_WINDOW_INTERFACE )


    /* dummy video application */
    DEFINE_CLASS( TI_MUI_TEST_VIDEO_CALLS)

/* ************************************************************************
**    LISA CLASSES
** ********************************************************************* */
/* Event Manager */
DEFINE_CLASS( TL_EM_KERNEL )

/* CPM classes */

DEFINE_CLASS( TL_CPM_SIM_REFRESH )
DEFINE_CLASS( TL_CPM_ALTERNATE_LINE_SERVICE )
DEFINE_CLASS( TL_CPM_CLIENT_CONSTRAINT )
DEFINE_CLASS( TL_CPM_ACQUIRE_CAPABILITY )
DEFINE_CLASS( TL_CPM_PROFILE )
DEFINE_CLASS( TL_CPM_CAPABILITY_GROUPS )
DEFINE_CLASS( TL_CPM_EVENT_NOTIFICATION )
DEFINE_CLASS( TL_CPM_CUSTOMER_SERVICE_PROFILE )
DEFINE_CLASS( TL_CPM_CONFIGURATION_SETUP )
DEFINE_CLASS( TL_CPM_IMSI_DECODE )
DEFINE_CLASS( TL_CPM_PROCESS_SIGNAL )
DEFINE_CLASS( TI_CPM_INTERFACE )
DEFINE_CLASS( TL_CPM_SYSTEM_SERVICE_SETUP )
DEFINE_CLASS( TL_CPM_SYSTEM_PROFILE_TLV_DATA )


/* Language Control */
DEFINE_CLASS( TI_LNCT_INTERFACE )


/* Language Database */


/* File Manager Class*/
DEFINE_CLASS( TI_FMGR_INTERFACE )





/* All the classes must be defined here */
DEFINE_CLASS( C_SL_NWRK_TEST )
DEFINE_CLASS( C_SL_RXLEVEL )
DEFINE_CLASS( C_SL_CSREGISTRATION )
DEFINE_CLASS( C_SL_PLMNBUILDER )
DEFINE_CLASS( C_SL_NWRK_SIGNAL_DECODER )
DEFINE_CLASS( TI_NWRK_INTERFACE )
DEFINE_CLASS( C_SL_LISA_MMI_BRIDGE )
DEFINE_CLASS( C_SL_RNA_BRIDGE )
DEFINE_CLASS( C_SL_MMI_LISA_BRIDGE )
DEFINE_CLASS( C_SL_PLMN_DB )
DEFINE_CLASS( C_SL_LOCAL_ZONE )
DEFINE_CLASS( C_SL_NWRK_MANAGER )



DEFINE_CLASS( C_SS_USSD_REQUEST)
DEFINE_CLASS( C_SS_USSD_API)
DEFINE_CLASS( C_SS_LIBRARY)
DEFINE_CLASS( C_SS_LISA_BRIDGE)

/* SAT Server classes */
DEFINE_CLASS( TI_SATS_INTERFACE )
DEFINE_CLASS( TL_SATS_PCMD_SESSION )
DEFINE_CLASS( TL_SATS_PERFORM_PCOMMANDS )
DEFINE_CLASS( TI_SATS_RUN_AT_CMD )
/* vvv 030831 DNES T.Kitai for Add Class ID of SATS */
DEFINE_CLASS( TL_SATS_CHANNEL )
/* ^^^ 030831 DNES T.Kitai for Add Class ID of SATS */

/* C_SM_APPLICATION_PROJECT */
DEFINE_CLASS( C_APM_STUB_MANAGER )
DEFINE_CLASS( C_APM_STUB_APPLICATION )

/* MATT Server classes */
DEFINE_CLASS( TL_MAT_API_INTERFACE )
DEFINE_CLASS( TL_MAT_MANAGER )
DEFINE_CLASS( TL_MAT_MLP_IMP )
DEFINE_CLASS( TL_MAT_SERIAL_CONTROL )

/* OMP Simulator classes */
DEFINE_CLASS( TI_OMP_DOWN_INTERFACE )
DEFINE_CLASS( TI_OMP_UP_INTERFACE )

/* OMP classes */
DEFINE_CLASS( TL_OMP_L1 )
DEFINE_CLASS( TL_OMP_L2 )
DEFINE_CLASS( TL_OMP_L3 )
DEFINE_CLASS( TL_OMP_CONFIG)
DEFINE_CLASS( TL_OMP_SCM )
DEFINE_CLASS( TL_OMP_SCMSEARCH )
DEFINE_CLASS( TL_OMP_STCONTROL )

/* Test application for Lisa */
    DEFINE_CLASS( C_SM_TEST )
    DEFINE_CLASS( C_SM_TEST_NU_TIMER )


/* Security for Lisa */
DEFINE_CLASS( TL_SCM_HANDLE_MESSAGES )
DEFINE_CLASS( TI_SCS_INTERFACE )
DEFINE_CLASS( TL_SCS_VERIFY_PIN )
DEFINE_CLASS( TL_SCS_VERIFY_PHONE_CODE )
DEFINE_CLASS( TL_SCM_CHECK_PHONE_CODE_BARRED )
DEFINE_CLASS( TL_SCM_SECURITY_POWERUP_CHECKS )


/* PS SIMULATOR */
DEFINE_CLASS( TC_PSS_CALL )
DEFINE_CLASS( TC_PSS_CALL_CONTROL )
DEFINE_CLASS( TC_PSS_NWRK_SERVICE )
DEFINE_CLASS( TC_PSS_NWRK_RXLEVEL )
DEFINE_CLASS( TC_PSS_SMS)
DEFINE_CLASS( TC_PSS_SMS_CONTROL)
DEFINE_CLASS( TC_PSS_PDP_CALL)
DEFINE_CLASS( TC_PSS_PDP_CONTROL)
DEFINE_CLASS( TC_PSS_DATA_CALL)
DEFINE_CLASS( TC_PSS_SMS_CB )
DEFINE_CLASS( TC_PSS_CISS)
DEFINE_CLASS( TC_PSS_CISS_CONTROL)
DEFINE_CLASS( TC_PSS_NWRK_PLMN)
DEFINE_CLASS( TC_PSS_AUTO_CHARGE_UNITS)
DEFINE_CLASS( TC_PSS_AUTO_CHARGE)

/* TLLC SIMULATOR */
DEFINE_CLASS( TL_TLLC_SIMULATOR )
/* AoC Class */
DEFINE_CLASS( TL_CNM_AOC )


/* ************************************************************************
**    DET Dialog Editor Tool CLASSES
** ********************************************************************* */
    DEFINE_CLASS( TC_DET_PREVIEW )  /* this is used by c_ui_test project */


/* CSDA classes */
    DEFINE_CLASS( TL_CSDA_MANAGEMENT )

/*LNA Classes*/
DEFINE_CLASS( TL_LNA_CTRL )
DEFINE_CLASS( TL_LNA_OMP )
DEFINE_CLASS( TL_LNA_AT )
DEFINE_CLASS( TL_LNA_AUP )
/* NECrg17440 CAA classes */
//    DEFINE_CLASS( TL_CAA_ADAPTER )

/* NECrg17440 Test under ACPU, but later need to move to CCPU */
//    DEFINE_CLASS( TL_CAC_ADAPTER )

/* PPP Define Classes */
    
    DEFINE_CLASS( TL_PPP_MANAGER )
    DEFINE_CLASS( TL_PPP_HDLC )
    DEFINE_CLASS( TL_PPP_CTRL_PROT_FSM )
    DEFINE_CLASS( TL_PPP_LAYER )
    DEFINE_CLASS( TL_PPP_VJCOMPRESSION )
    DEFINE_CLASS( TL_PPP_SERVICE )
    DEFINE_CLASS( TL_PPP_PKT_FIFO )
    DEFINE_CLASS( TL_PPP_LCP )
    DEFINE_CLASS( TL_PPP_PAP )
    DEFINE_CLASS( TL_PPP_CHAP )
    DEFINE_CLASS( TL_PPP_IPCP )
    DEFINE_CLASS( TL_PPP_LCP_GW )

/* Application */
DEFINE_CLASS( C_MUI_TEST_SENDMAIL )
DEFINE_CLASS( C_MUI_SEND_EMAIL )
DEFINE_CLASS( C_MUI_RECEIVE_EMAIL )

/*LCS*/
DEFINE_CLASS( C_MUI_LCS )

/*Added by Steven 26/06/2003*/
DEFINE_CLASS(C_MUI_EZTEXT)


/*These are used for logging only*/
DEFINE_LOG_TYPE(STA)
DEFINE_LOG_TYPE(ENT)
DEFINE_LOG_TYPE(INT)
DEFINE_LOG_TYPE(EXT)
DEFINE_LOG_TYPE(TRA)

DEFINE_CLASS( TL_LNSC_CORE )

#undef DEFINE_CLASS
#undef DEFINE_LOG_TYPE



